### PR TITLE
Add MIT license headers

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Until [this topic is cleared](https://github.com/PrestaShop/phpstan-prestashop/issues/6) I add a minimalist license header inspired by [Symfony](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FullStack.php).
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | No need for test
| Possible impacts? |

### CODE REVIEW

**Comment by matks** [comment]
Funny, the CI passes on my computer but fails on GitHub. On GitHub license header lines are considered (so the line number is different) while on my computer, license header lines are ignored.

**Comment by PierreRambaud** [comment]
> Funny, the CI passes on my computer but fails on GitHub. On GitHub license header lines are considered (so the line number is different) while on my computer, license header lines are ignored.

**Comment by matks** [comment]
@PierreRambaud It makes me wonder what is the right behavior 😄  : my localhost or GitHub ? Both results have meaning

**Comment by PierreRambaud** [comment]
I confirm you the problem come from your localhost, I reproduce the GitHub actions' problems on my machine :trollface:

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @matks

**Comment by matks** [comment]
> I confirm you the problem come from your localhost

It cant be, it's an Apple product ! 🍎

**Pull request merged**
