### PR TITLE
Add ClassConstantsMustHaveVisibilityRule

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add ClassConstantsMustHaveVisibilityRule. This rule requires class constants to have a declared visibility.
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | One item of https://github.com/PrestaShop/PrestaShop/issues/22728
| How to test?      | CI is green
| Possible impacts? |

### CODE REVIEW

**Comment by matks** [comment]
The PR that modifies the code to comply with this rule is https://github.com/PrestaShop/PrestaShop/pull/23200/

**Review by Progi1984 — APPROVED** [review]
So beautiful

**Comment by Progi1984** [comment]
(May be add a test for private const) ;)

**Comment by matks** [comment]
> (May be add a test for private const) ;)

Added in https://github.com/PrestaShop/phpstan-prestashop/pull/5/commits/780affb6a96ea6594b5f62464f864aac6ad0ecd9

**Review by Progi1984 — APPROVED** [review]

**Pull request merged**
